name: Build and Test

on: [workflow_call] #[push] #temp disable
  #push:
    #branches: [main]
  #pull_request:
    #branches: [main]

jobs:
  initialize:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
  
  build_and_test:
    needs: initialize
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build "./RockLib.Collections/RockLib.Collections.csproj" --configuration Release --no-restore

      - name: Test
        run: dotnet test "./RockLib.Collections.Tests/RockLib.Collections.Tests.csproj" --no-restore --verbosity normal

  #ok_to_publish:
  #  needs: build_and_test
  #  runs-on: windows-latest
  #  environment: [EnviromentName]
  #  uses: ./.github/workflows/publish.yml
