name: Build and Test

####################################################################################################
##  WORKFLOW TRIGGER
####################################################################################################
on:
  # Workflow will run on any pull request to main.
  pull_request:
    branches:
      - main

####################################################################################################
##  WORKFLOW JOBS
####################################################################################################
jobs:
  build_and_test:
    name: Build and test projects
    # Using the latest Windows GitHub-hosted runner.
    runs-on: windows-latest
    # The matrix is used to define the frameworks that the project(s) support.
    # For each value in the matrix a concurrent version of the job is run using that value.
    strategy:
      matrix:
        target_framework: [ net6.0, netcoreapp3.1, net48 ]

    steps:
      # Using Github checkout action to retrieve the codebase.
      - name: Fetch code
        uses: actions/checkout@v3
      
      # Using dotnet build to build the solution using a target framework specified in the matrix.
      - name: Build ${{ matrix.target_framework }}
        run: dotnet build --configuration Release --framework ${{ matrix.target_framework }}
      
      # Using dotnet test to run any unit tests found in the solution using a target framework specified in the matrix.
      # If any test fails, the job and workflow will fail.
      - name: Test ${{ matrix.target_framework }}
        run: dotnet test --configuration Release --no-build --verbosity normal --framework ${{ matrix.target_framework }}
