name: Build and Test

on: [push] #Other interesting triggers: pull_request, release, workflow_call, fork

jobs:
  initialize:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
  
  build_and_test:
    needs: initialize
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build "RockLib.Collections.sln" --configuration Release --no-restore

      - name: Test
        run: dotnet test "RockLib.Collections.sln" --no-restore --verbosity normal
