name: Build and Test

on: [workflow_call] #[push] #temp disable
  #push:
    #branches: [main]
  #pull_request:
    #branches: [main]

jobs:
  initialize:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x', '6.0.x']

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
  
  build_and_test:
    needs: initialize
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: dotnet restore

        #${{ github.repository }} - owner/repo 
        #${{ github.event.repository.name }} - repo name 
        #${{ github.repository_owner }} - repo owner name 
        #See check-diff.yml for a job to get this branch name

        #Can build and test off the top level sln
      - name: Get .sln
        shell: pwsh
        run: |
          $sln = Get-ChildItem "*.sln" -Name
          echo "SLN_NAME=$sln" >> $env:GITHUB_ENV

      - name: Build
        run: dotnet build "./${{ env.SLN_NAME }}" --configuration Release --no-restore
        
      - name: Test
        run: dotnet test "./${{ env.SLN_NAME }}" --no-restore --verbosity normal #**Tests.csproj

  call_publish:
    needs: build_and_test
    uses: ./.github/workflows/publish.yml
