name: Check Diff

on:
  [push, pull_request] #workflow_call:

jobs:
  print_package_version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Version
        run: |
          $csproj_path = "./RockLib.Collections.csproj"
          $csproj = [xml](Get-Content -Path $csproj_path)
          $package_id = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageVersion").InnerText
          $package_version = $csproj.SelectSingleNode("/Project/PropertyGroup/PackageVersion").InnerText

          echo "$csproj_path"
          echo "$package_id"
          echo "$package_version"

  check_diff:
    
    runs-on: windows-latest

    outputs: 
      diff: ${{ steps.output-tojson.outputs.diff }}
      hasChanges: ${{ steps.check-diff.outputs.hasChanges }}
  
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Get branch name (not pull request)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Check Diff
        id: check-diff
        #gh api -H "Accept:application/vnd.github.diff" repos/RockLib/RockLib.Collections/compare/main...${{ env.BRANCH_NAME }}
        shell: pwsh
        run: |
          #Get the diff between this branch and main
          $diff = git diff --name-only origin/main..${{ env.BRANCH_NAME }}

          #Find any changed csproj files and if it has any set hasChanges to true
          $projChanged = $diff | Where-Object { $_ -match '.csproj$' } #(DiffHere).Remove(0, $diff.IndexOf('/') + 1)
          $hasChanges = $projChanged.Length -gt 0

          #Debugging
          echo "$diff"
          echo "$projChanged"
          echo "$hasChanges"

          #If 1+ projects changed: split the diff on spaces into an array
          if ($hasChanges) {
            $projChanged = $projChanged.split(" ")
            $projChangedJSON = ConvertTo-Json -Compress $projChanged
            $projChangedJSON = "{`"include`":$projChangedJSON}"
          }
          echo "$projChangedJSON"
          #echo "$fromJSON($projChanged)"
          #echo "$toJSON($projChanged)"
          
          #Output
          echo "::set-output name=hasChanges::$hasChanges"
          #echo "::set-output name=diff::$projChangedJSON"
          echo "projChangedJSON=$projChangedJSON" >> $GITHUB_ENV #Try saving as an env to output in another step.
          echo "::set-output name=diff::${{ env.projChangedJSON }}"
          
      - name: Test Step
        run: |
          echo "${{ env.projChangedJSON }}"
          echo "$fromJSON(${{ env.projChangedJSON }})"
          echo "$toJSON(${{ env.projChangedJSON }})"
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  #Use a job with a matrix strategy to define a job for each package.
  #DONE keep the diff from above
  #TODO search for specific package changes for each job.
  #https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
  test_job:
    needs: check_diff
    runs-on: windows-latest
    if: needs.check_diff.outputs.hasChanges == 'True'
    steps: 
      - name: View output value
        run: |
          #echo "${{ fromJSON(needs.check_diff.outputs.diff) }}"

          $arrayFromJson = ConvertFrom-Json ${{ needs.check_diff.outputs.diff }}
          echo "$arrayFromJson"
          
    

  ok_to_publish:
    needs: check_diff
    runs-on: windows-latest
    if: needs.check_diff.outputs.hasChanges == 'True'
    strategy:
      matrix: 
        package: ${{ fromJSON(needs.check_diff.outputs.diff) }}
    name: ${{ matrix.include }} #Ok to Publish
        

    steps:
      - name: Has Diff
        run: echo "${{ matrix.package }}"
