name: Check Diff

on:
  [push, pull_request]

jobs:
  check-diff:
    
    runs-on: windows-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Get branch name (not pull request)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV

      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

    #  - name: Debug
    #    run: echo ${{ env.BRANCH_NAME }}

      - name: Check Diff
        run: gh api -H "Accept:application/vnd.github.diff" repos/RockLib/RockLib.Collections/compare/main...${{ env.BRANCH_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #THIS_BRANCH: ${{ env.BRANCH_NAME }}
