name: Snyk Test

####################################################################################################
##  WORKFLOW TRIGGER
####################################################################################################
on:
  # Workflow will run after build_and_test is completed.
  workflow_run:
    workflows: [ Build and Test ]
    types: [ completed ]

####################################################################################################
##  WORKFLOW JOBS
####################################################################################################
jobs:
  # Calls the shared snyk-test workflow.
  call_snyk_test:
    name: Call snyk-test workflow
    uses: .github/workflows/snyk-test.yml
    secrets: inherit