name: Run Unit Test

####################################################################################################
##  WORKFLOW TRIGGER
####################################################################################################
on:
  pull_request:
    branches: [ main ]

####################################################################################################
##  WORKFLOW JOBS
####################################################################################################
jobs:
  # Calls the shared unit-test workflow.
  call_unit_test:
    name: Call unit-test workflow
    uses: ./.github/workflows/unit-test.yml
    secrets: inherit
